name: Mskyblock
main: mskyblock.Main
version: "2.1.1"
author: maru
api: ["1.0.6"]

permissions:
 mskyblock.*:
  default: OP
  children:
   mskyblock.commands.*:
    default: true
    children:
     mskyblock.commands.island:
      default: true
   mskyblock.remove.other:
    default: OP
